const zenoOfCitium = [
  "The goal of life is living in agreement with nature. - Zeno of Citium",
  "Happiness is a good flow of life. - Zeno of Citium",
  "Well-being is realized by small steps, but is truly no small thing. - Zeno of Citium",
  "Man conquers the world by conquering himself. - Zeno of Citium",
  "Lack of activity destroys the good condition of every human being, while movement and methodical physical exercise save it and preserve it. - Zeno of Citium",
  "A bad feeling is a commotion of the mind repugnant to reason, and against nature. - Zeno of Citium",
  "A friend is a second self. - Zeno of Citium",
  "The wise man belongs to all countries, for the home of a great soul is the whole world. - Zeno of Citium",
  "We have two ears and one mouth, so we should listen more than we say. - Zeno of Citium",
  "What need is there to weep over parts of life? The whole of it calls for tears. - Zeno of Citium",
  "Attach yourself to what is spiritually superior, regardless of what other people think or do. Hold to your true aspirations no matter what is going on around you. - Zeno of Citium",
  "We are more often frightened than hurt; and we suffer more from imagination than from reality. - Zeno of Citium",
  "Wealth is a sick man's gold. - Zeno of Citium",
  "Nothing great is created suddenly, any more than a bunch of grapes or a fig. If you tell me that you desire a fig, I answer you that there must be time. Let it first blossom, then bear fruit, then ripen. - Zeno of Citium",
  "We have received this body, which is exposed to all kinds of suffering, as a good loan. Let us not exact too high a rate of interest for it. - Zeno of Citium",
  "The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not. - Zeno of Citium",
  "To be overcome by the fragrance of flowers is a delectable form of defeat. - Zeno of Citium",
  "The most beautiful ornament is virtue. - Zeno of Citium",
  "Fate leads the willing and drags along the reluctant. - Zeno of Citium",
  "The goal of life is living in agreement with nature. - Zeno of Citium",
  "The reason why we have two ears and only one mouth is that we may listen the more and talk the less. - Zeno of Citium",
  "No evil can happen to a good man, either in life or after death. - Zeno of Citium",
  "The wise man is neither raised up by prosperity nor cast down by adversity. - Zeno of Citium",
  "Happiness is a good flow of life. - Zeno of Citium",
  "If you lay violent hands on me, you will have my body, but my soul will escape you. - Zeno of Citium",
  "Better to trip with the feet than with the tongue. - Zeno of Citium",
  "No loss should be more regrettable to us than losing our time, for without time all other loss is irreparable. - Zeno of Citium",
  "The goal of life is living in agreement with nature. - Zeno of Citium",
  "The greatest and most divine gifts are given to us free of charge. - Zeno of Citium",
  "The end may be defined as life in accordance with nature, or, in other words, in accordance with our own human nature as well as that of the universe. - Zeno of Citium",
  "The voice is the flower of beauty. - Zeno of Citium",
  "Steal not this moment from the future. - Zeno of Citium",
  "The cry of a newborn baby is nature’s way of warning us that we have made a big mistake. - Zeno of Citium",
  "A bad feeling is a commotion of the mind repugnant to reason, and against nature. - Zeno of Citium",
  "It is better to trip with the feet than with the tongue. - Zeno of Citium",
  "Love is a God, who cooperates in securing the safety of the city. - Zeno of Citium",
  "The most necessary learning is that which unlearns evil. - Zeno of Citium",
  "Nothing is more hostile to a firm grasp on knowledge than self-deception. - Zeno of Citium",
  "It is the power of the mind to be unconquerable. - Zeno of Citium",
  "If you want to improve, be content to be thought foolish and stupid. - Zeno of Citium",
  "Fate is the endless chain of causation, whereby things are; the reason or formula by which the world goes on. - Zeno of Citium",
  "Man conquers the world by conquering himself. - Zeno of Citium",
  "A good character is the only guarantee of everlasting, carefree happiness. - Zeno of Citium",
  "The goal of life is living in agreement with nature. - Zeno of Citium",
  "Happiness is a good flow of life. - Zeno of Citium",
  "No matter how busy you may think you are, you must find time for reading, or surrender yourself to self-chosen ignorance. - Zeno of Citium",
  "Well-being is realized by small steps, but is truly no small thing. - Zeno of Citium",
  "Man conquers the world by conquering himself. - Zeno of Citium",
];

const epictetus = [
  "It's not what happens to you, but how you react to it that matters. - Epictetus",
  "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
  "Man is not worried by real problems so much as by his imagined anxieties about real problems. - Epictetus",
  "First say to yourself what you would be; and then do what you have to do. - Epictetus",
  "No man is free who is not master of himself. - Epictetus",
  "Don't explain your philosophy. Embody it. - Epictetus",
  "Only the educated are free. - Epictetus",
  "The key is to keep company only with people who uplift you, whose presence calls forth your best. - Epictetus",
  "He who laughs at himself never runs out of things to laugh at. - Epictetus",
  "If you want to improve, be content to be thought foolish and stupid. - Epictetus",
  "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. - Epictetus",
  "The greater the difficulty, the more glory in surmounting it. Skillful pilots gain their reputation from storms and tempests. - Epictetus",
  "Circumstances don't make the man, they only reveal him to himself. - Epictetus",
  "We should always be asking ourselves: 'Is this something that is, or is not, in my control?' - Epictetus",
  "Know, first, who you are, and then adorn yourself accordingly. - Epictetus",
  "People are not disturbed by things, but by the views they take of them. - Epictetus",
  "If you wish to be a writer, write. - Epictetus",
  "Make the best use of what is in your power, and take the rest as it happens. - Epictetus",
  "It is impossible for a man to learn what he thinks he already knows. - Epictetus",
  "He who is not happy with little will never be happy with much. - Epictetus",
  "Seek not the good in external things; seek it in yourselves. - Epictetus",
  "No great thing is created suddenly. - Epictetus",
  "To accuse others for one's own misfortunes is a sign of want of education. To accuse oneself shows that one's education has begun. To accuse neither oneself nor others shows that one's education is complete. - Epictetus",
  "Attach yourself to what is spiritually superior, regardless of what other people think or do. Hold to your true aspirations no matter what is going on around you. - Epictetus",
  "Men are disturbed not by things, but by the views which they take of them. - Epictetus",
  "If evil be said of thee, and if it be true, correct thyself; if it be a lie, laugh at it. - Epictetus",
  "Be careful to leave your sons well instructed rather than rich, for the hopes of the instructed are better than the wealth of the ignorant. - Epictetus",
  "Do not seek to bring things to pass in accordance with your wishes, but wish for them as they are, and you will find them. - Epictetus",
  "When you are offended at any man's fault, turn to yourself and study your own failings. Then you will forget your anger. - Epictetus",
  "First learn the meaning of what you say, and then speak. - Epictetus",
  "Neither should a ship rely on one small anchor, nor should life rest on a single hope. - Epictetus",
  "We are not disturbed by what happens to us, but by our thoughts about what happens to us. - Epictetus",
  "To know how to behave is easy; to know what to do is hard. - Epictetus",
  "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. - Epictetus",
  "If you would be a reader, read; if a writer, write. - Epictetus",
  "When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love. - Epictetus",
  "The essence of philosophy is that a man should so live that his happiness shall depend as little as possible on external things. - Epictetus",
  "It is not death or pain that is to be dreaded, but the fear of pain or death. - Epictetus",
  "Seek not the good in external things; seek it in yourselves. - Epictetus",
  "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will. - Epictetus",
  "The flourishing life cannot be achieved until we moderate our desires and see how superficial and fleeting they are. - Epictetus",
  "If someone speaks badly of you, do not defend yourself against the accusations, but reply; 'You obviously don't know me very well, since there are so many other faults you could have mentioned.' - Epictetus",
  "Who is rich? He who is content. Who is that? Nobody. - Epictetus",
  "No person is free who is not master of himself. - Epictetus",
  "It is not the things themselves that disturb people, but their judgments about these things. - Epictetus",
  "We cannot choose our external circumstances, but we can always choose how we respond to them. - Epictetus",
  "You become what you give your attention to. - Epictetus",
  "A ship should not ride on a single anchor, nor life on a single hope. - Epictetus",
];
const senecaTheYounger = [
  "Luck is what happens when preparation meets opportunity. - Seneca the Younger",
  "All cruelty springs from weakness. - Seneca the Younger",
  "True happiness is to enjoy the present, without anxious dependence upon the future. - Seneca the Younger",
  "It is not the man who has too little, but the man who craves more, that is poor. - Seneca the Younger",
  "We suffer more often in imagination than in reality. - Seneca the Younger",
  "Difficulties strengthen the mind, as labor does the body. - Seneca the Younger",
  "As is a tale, so is life: not how long it is, but how good it is, is what matters. - Seneca the Younger",
  "He suffers more than necessary, who suffers before it is necessary. - Seneca the Younger",
  "It is the power of the mind to be unconquerable. - Seneca the Younger",
  "He who is brave is free. - Seneca the Younger",
  "Begin at once to live, and count each separate day as a separate life. - Seneca the Younger",
  "While we wait for life, life passes. - Seneca the Younger",
  "Sometimes even to live is an act of courage. - Seneca the Younger",
  "The greatest remedy for anger is delay. - Seneca the Younger",
  "If a man knows not to which port he sails, no wind is favorable. - Seneca the Younger",
  "We are more often frightened than hurt; and we suffer more from imagination than from reality. - Seneca the Younger",
  "It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult. - Seneca the Younger",
  "Wealth is the slave of a wise man and the master of a fool. - Seneca the Younger",
  "Most powerful is he who has himself in his own power. - Seneca the Younger",
  "The whole future lies in uncertainty: live immediately. - Seneca the Younger",
  "He who has great power should use it lightly. - Seneca the Younger",
  "Wherever there is a human being, there is an opportunity for a kindness. - Seneca the Younger",
  "Time heals what reason cannot. - Seneca the Younger",
  "No man was ever wise by chance. - Seneca the Younger",
  "Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it. - Seneca the Younger",
  "No evil propensity of the human heart is so powerful that it may not be subdued by discipline. - Seneca the Younger",
  "A gem cannot be polished without friction, nor a man perfected without trials. - Seneca the Younger",
  "One of the most beautiful qualities of true friendship is to understand and to be understood. - Seneca the Younger",
  "To wish to be well is a part of becoming well. - Seneca the Younger",
  "To be evenminded is the greatest virtue. - Seneca the Younger",
  "Every new beginning comes from some other beginning's end. - Seneca the Younger",
  "Consult your friend on all things, especially on those which respect yourself. - Seneca the Younger",
  "No man can have a peaceful life who thinks too much about lengthening it. - Seneca the Younger",
  "The bravest sight in the world is to see a great man struggling against adversity. - Seneca the Younger",
  "Let us train our minds to desire what the situation demands. - Seneca the Younger",
  "We learn not in the school, but in life. - Seneca the Younger",
  "He who dreads hostility too much is unfit to rule. - Seneca the Younger",
  "A happy life is one which is in accordance with its own nature. - Seneca the Younger",
  "Constant exposure to dangers will breed contempt for them. - Seneca the Younger",
  "Associate with people who are likely to improve you. - Seneca the Younger",
  "No untroubled day has ever dawned for me. - Seneca the Younger",
  "If you really want to escape the things that harass you, what you’re needing is not to be in a different place but to be a different person. - Seneca the Younger",
  "Life, if well lived, is long enough. - Seneca the Younger",
  "The mind that is anxious about future events is miserable. - Seneca the Younger",
  "To be everywhere is to be nowhere. - Seneca the Younger",
  "Let us say what we feel, and feel what we say; let speech harmonize with life. - Seneca the Younger",
  "It is a rough road that leads to the heights of greatness. - Seneca the Younger",
  "Enjoy present pleasures in such a way as not to injure future ones. - Seneca the Younger",
  "There is no easy way from the earth to the stars. - Seneca the Younger",
];
const marcusAurelius = [
  "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
  "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
  "It is not death that a man should fear, but he should fear never beginning to live. - Marcus Aurelius",
  "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
  "When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love. - Marcus Aurelius",
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. - Marcus Aurelius",
  "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
  "He who lives in harmony with himself lives in harmony with the universe. - Marcus Aurelius",
  "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
  "The universe is change; our life is what our thoughts make it. - Marcus Aurelius",
  "If it is not right, do not do it; if it is not true, do not say it. - Marcus Aurelius",
  "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane. - Marcus Aurelius",
  "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look. - Marcus Aurelius",
  "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart. - Marcus Aurelius",
  "Reject your sense of injury and the injury itself disappears. - Marcus Aurelius",
  "To live happily is an inward power of the soul. - Marcus Aurelius",
  "He who has a why to live can bear almost any how. - Marcus Aurelius",
  "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present. - Marcus Aurelius",
  "How much more grievous are the consequences of anger than the causes of it. - Marcus Aurelius",
  "Do every act of your life as if it were your last. - Marcus Aurelius",
  "Our life is what our thoughts make it. - Marcus Aurelius",
  "The only wealth which you will keep forever is the wealth you have given away. - Marcus Aurelius",
  "It is not what happens to you, but how you react to it that matters. - Marcus Aurelius",
  "A man's worth is no greater than the worth of his ambitions. - Marcus Aurelius",
  "The art of living is more like wrestling than dancing. - Marcus Aurelius",
  "Whatever happens at all happens as it should; you will find this true, if you watch narrowly. - Marcus Aurelius",
  "Loss is nothing else but change, and change is nature's delight. - Marcus Aurelius",
  "Life is neither good or evil, but only a place for good and evil. - Marcus Aurelius",
  "Nowhere can man find a quieter or more untroubled retreat than in his own soul. - Marcus Aurelius",
  "Confine yourself to the present. - Marcus Aurelius",
  "Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig. - Marcus Aurelius",
  "What we do now echoes in eternity. - Marcus Aurelius",
  "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
  "The impediment to action advances action. What stands in the way becomes the way. - Marcus Aurelius",
  "If it is endurable, then endure it. Stop complaining. - Marcus Aurelius",
  "Whenever you are about to find fault with someone, ask yourself the following question: What fault of mine most nearly resembles the one I am about to criticize? - Marcus Aurelius",
  "Dwell on the beauty of life. Watch the stars, and see yourself running with them. - Marcus Aurelius",
  "Your mind will take the shape of what you frequently hold in thought, for the human spirit is colored by such impressions. - Marcus Aurelius",
  "To love only what happens, what was destined. No greater harmony. - Marcus Aurelius",
  "When you wake up in the morning, tell yourself: The people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous and surly. They are like this because they can’t tell good from evil. - Marcus Aurelius",
  "You could leave life right now. Let that determine what you do and say and think. - Marcus Aurelius",
  "What is not good for the bee-hive cannot be good for the bees. - Marcus Aurelius",
  "If someone is able to show me that what I think or do is not right, I will happily change, for I seek the truth, by which no one was ever truly harmed. It is the person who continues in his self-deception and ignorance who is harmed. - Marcus Aurelius",
  "When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love… - Marcus Aurelius",
  "Do not act as if you were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good. - Marcus Aurelius",
  "The best revenge is not to be like your enemy. - Marcus Aurelius",
  "Because a thing seems difficult for you, do not think it impossible for anyone to accomplish. - Marcus Aurelius",
  "Each day provides its own gifts. - Marcus Aurelius",
  "That which is not good for the bee-hive cannot be good for the bees. - Marcus Aurelius",
];
const cleanthes = [
  "Lead me, Zeus, and you, Fate, wherever you have assigned me. I shall follow without hesitation; but even if I refuse, I shall follow no less surely. - Cleanthes",
  "Fate guides the willing, but drags the unwilling. - Cleanthes",
  "If you lay violent hands on me, you will have my body, but my soul will escape you. - Cleanthes",
  "He who has learned to die has unlearned to serve. - Cleanthes",
  "Do not seek to bring things to pass in accordance with your wishes, but wish for them as they are, and you will find them. - Cleanthes",
  "He who lives in harmony with himself lives in harmony with the universe. - Cleanthes",
  "We should be doing something worthwhile, that is, something that will eventually be of benefit to mankind. - Cleanthes",
  "Our fate is in our own hands. - Cleanthes",
  "It is not the things themselves that disturb men, but their opinions about these things. - Cleanthes",
  "No one entrusts a secret to a drunken man; but one will entrust a secret to a man who is self-controlled. - Cleanthes",
  "The reason why we have two ears and only one mouth is that we may listen the more and talk the less. - Cleanthes",
  "Be tranquil at the prospect of change. - Cleanthes",
  "The wise man is neither raised up by prosperity nor cast down by adversity. - Cleanthes",
  "We must train ourselves to let go of the things we cannot control. - Cleanthes",
  "Those who receive an injury are not at fault for it, but those who inflict it. - Cleanthes",
  "Happiness is not a matter of events; it depends upon the tides of the mind. - Cleanthes",
  "First say to yourself what you would be; and then do what you have to do. - Cleanthes",
  "Man is disturbed not by things, but by the views he takes of them. - Cleanthes",
  "Nothing is more honorable than a grateful heart. - Cleanthes",
  "Accept whatever comes to you woven in the pattern of your destiny, for what could more aptly fit your needs? - Cleanthes",
  "The universe is change; our life is what our thoughts make it. - Cleanthes",
  "To accuse others for one's own misfortunes is a sign of want of education. To accuse oneself shows that one's education has begun. To accuse neither oneself nor others shows that one's education is complete. - Cleanthes",
  "He who lives in harmony with himself lives in harmony with the universe. - Cleanthes",
  "True happiness is to enjoy the present, without anxious dependence upon the future. - Cleanthes",
  "To live happily is an inward power of the soul. - Cleanthes",
  "If a man knows not to which port he sails, no wind is favorable. - Cleanthes",
  "Seek not the good in external things; seek it in yourselves. - Cleanthes",
  "We are not disturbed by what happens to us, but by our thoughts about what happens to us. - Cleanthes",
  "Do not explain your philosophy. Embody it. - Cleanthes",
  "The key is to keep company only with people who uplift you, whose presence calls forth your best. - Cleanthes",
  "He who laughs at himself never runs out of things to laugh at. - Cleanthes",
  "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. - Cleanthes",
  "The greater the difficulty, the more glory in surmounting it. Skillful pilots gain their reputation from storms and tempests. - Cleanthes",
  "Circumstances don't make the man, they only reveal him to himself. - Cleanthes",
  "We should always be asking ourselves: 'Is this something that is, or is not, in my control?' - Cleanthes",
  "Know, first, who you are, and then adorn yourself accordingly. - Cleanthes",
  "If you wish to be a writer, write. - Cleanthes",
  "Make the best use of what is in your power, and take the rest as it happens. - Cleanthes",
  "It is impossible for a man to learn what he thinks he already knows. - Cleanthes",
  "He who is not happy with little will never be happy with much. - Cleanthes",
  "Seek not the good in external things; seek it in yourselves. - Cleanthes",
  "No great thing is created suddenly. - Cleanthes",
  "Wealth consists not in having great possessions, but in having few wants. - Cleanthes",
  "A bad feeling is a commotion of the mind repugnant to reason, and against nature. - Cleanthes",
  "A friend is a second self. - Cleanthes",
  "The wise man belongs to all countries, for the home of a great soul is the whole world. - Cleanthes",
  "We have two ears and one mouth, so we should listen more than we say. - Cleanthes",
  "What need is there to weep over parts of life? The whole of it calls for tears. - Cleanthes",
  "To be overcome by the fragrance of flowers is a delectable form of defeat. - Cleanthes",
  "The most beautiful ornament is virtue. - Cleanthes",
];
const chrysippus = [
  "As long as a person is in the process of learning, they are not ignorant. - Chrysippus",
  "He who is running against time cannot afford to wait for the perfect moment. - Chrysippus",
  "The universe itself is God and the universal outpouring of its soul. - Chrysippus",
  "The wise man is neither raised up by prosperity nor cast down by adversity. - Chrysippus",
  "We should try by all means to conform to nature, our own and the universe's. - Chrysippus",
  "Good can exist without evil, whereas evil cannot exist without good. - Chrysippus",
  "Virtue alone is the good. - Chrysippus",
  "Happiness is a good flow of life. - Chrysippus",
  "Live according to nature. - Chrysippus",
  "The purpose of life is happiness, which is secured by virtue, as much as virtue is sustained by reason. - Chrysippus",
  "We have art so that we do not die of reality. - Chrysippus",
  "Fate leads the willing and drags along the reluctant. - Chrysippus",
  "A wise man is prepared for everything. - Chrysippus",
  "The goal of life is living in agreement with nature. - Chrysippus",
  "He who has a why to live can bear almost any how. - Chrysippus",
  "We should treat each moment as if it were our last. - Chrysippus",
  "The soul is a mixture of fire and water. - Chrysippus",
  "No one is a slave who is free in their mind. - Chrysippus",
  "Do not seek to bring things to pass in accordance with your wishes, but wish for them as they are, and you will find them. - Chrysippus",
  "The wise man seeks always to live in harmony with nature. - Chrysippus",
  "The best way to defend oneself is not to do anything wrong. - Chrysippus",
  "The measure of a man is his ability to live in harmony with the universe. - Chrysippus",
  "Good actions give strength to ourselves and inspire good actions in others. - Chrysippus",
  "The wise man is content with his lot, whatever it may be, without wishing for what he has not. - Chrysippus",
  "The greatest wealth is to live content with little. - Chrysippus",
  "Do not explain your philosophy. Embody it. - Chrysippus",
  "To be even-minded is the greatest virtue. - Chrysippus",
  "The soul is dyed with the color of its thoughts. - Chrysippus",
  "The wise man does not grieve for what he has not, but rejoices in what he has. - Chrysippus",
  "Man is not worried by real problems so much as by his imagined anxieties about real problems. - Chrysippus",
  "The art of living is more like wrestling than dancing. - Chrysippus",
  "The purpose of life is to follow reason and virtue. - Chrysippus",
  "The only way to happiness is to cease worrying about things which are beyond the power of our will. - Chrysippus",
  "We cannot choose our external circumstances, but we can always choose how we respond to them. - Chrysippus",
  "The wise man is neither raised up by prosperity nor cast down by adversity. - Chrysippus",
  "If you want to improve, be content to be thought foolish and stupid. - Chrysippus",
  "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. - Chrysippus",
  "It is not what happens to you, but how you react to it that matters. - Chrysippus",
  "To accuse others for one's own misfortunes is a sign of want of education. To accuse oneself shows that one's education has begun. To accuse neither oneself nor others shows that one's education is complete. - Chrysippus",
  "The universe is change; our life is what our thoughts make it. - Chrysippus",
  "We are more often frightened than hurt; and we suffer more from imagination than from reality. - Chrysippus",
  "Wealth consists not in having great possessions, but in having few wants. - Chrysippus",
  "The whole future lies in uncertainty: live immediately. - Chrysippus",
  "Most powerful is he who has himself in his own power. - Chrysippus",
  "To live happily is an inward power of the soul. - Chrysippus",
  "He who has great power should use it lightly. - Chrysippus",
  "The wise man belongs to all countries, for the home of a great soul is the whole world. - Chrysippus",
  "A friend is a second self. - Chrysippus",
  "The measure of a man is the way he bears up under misfortune. - Chrysippus",
];
const cicero = [
  "A room without books is like a body without a soul. - Cicero",
  "Gratitude is not only the greatest of virtues, but the parent of all the others. - Cicero",
  "If you have a garden and a library, you have everything you need. - Cicero",
  "The life of the dead is placed in the memory of the living. - Cicero",
  "Friendship improves happiness and abates misery, by the doubling of our joy and the dividing of our grief. - Cicero",
  "Times are bad. Children no longer obey their parents, and everyone is writing a book. - Cicero",
  "It is not by muscle, speed, or physical dexterity that great things are achieved, but by reflection, force of character, and judgment. - Cicero",
  "While there's life, there's hope. - Cicero",
  "The greater the difficulty, the greater the glory. - Cicero",
  "Any man can make mistakes, but only an idiot persists in his error. - Cicero",
  "The function of wisdom is to discriminate between good and evil. - Cicero",
  "Silence is one of the great arts of conversation. - Cicero",
  "The authority of those who teach is often an obstacle to those who want to learn. - Cicero",
  "The wise are instructed by reason, average minds by experience, the stupid by necessity and the brute by instinct. - Cicero",
  "To study philosophy is nothing but to prepare one's self to die. - Cicero",
  "The sinews of war are infinite money. - Cicero",
  "Brevity is the best recommendation of speech, whether in a senator or an orator. - Cicero",
  "Natural ability without education has more often attained to glory and virtue than education without natural ability. - Cicero",
  "He who has a garden and a library wants for nothing. - Cicero",
  "In a republic this rule ought to be observed: that the majority should not have the predominant power. - Cicero",
  "Justice is the set and constant purpose which gives every man his due. - Cicero",
  "The foundation of justice is good faith. - Cicero",
  "The shifts of Fortune test the reliability of friends. - Cicero",
  "The pursuit, even of the best things, ought to be calm and tranquil. - Cicero",
  "The greater the obstacle, the more glory in overcoming it. - Cicero",
  "The safety of the people shall be the highest law. - Cicero",
  "What is morally wrong can never be advantageous, even when it enables you to make some gain that you believe to be to your advantage. - Cicero",
  "A thankful heart is not only the greatest virtue, but the parent of all the other virtues. - Cicero",
  "Memory is the treasury and guardian of all things. - Cicero",
  "The life given us, by nature is short; but the memory of a well-spent life is eternal. - Cicero",
  "If we are not ashamed to think it, we should not be ashamed to say it. - Cicero",
  "The precepts of the law are these: to live honestly, to injure no one, and to give everyone else his due. - Cicero",
  "The wise are always ready to learn. - Cicero",
  "To be ignorant of what occurred before you were born is to remain always a child. - Cicero",
  "Nothing is more noble, nothing more venerable, than fidelity. - Cicero",
  "It is not by muscle, speed, or physical dexterity that great things are achieved, but by reflection, force of character, and judgment. - Cicero",
  "Cultivation to the mind is as necessary as food to the body. - Cicero",
  "There is no place more delightful than one's own fireplace. - Cicero",
  "There are more men ennobled by study than by nature. - Cicero",
  "Gratitude is not only the greatest of virtues, but the parent of all the others. - Cicero",
  "The wise man is always similar to himself. - Cicero",
  "Knowledge which is divorced from justice, may be called cunning rather than wisdom. - Cicero",
  "The more laws, the less justice. - Cicero",
  "The pursuit of truth and beauty is a sphere of activity in which we are permitted to remain children all our lives. - Cicero",
  "What sweetness is left in life, if you take away friendship? Robbing life of friendship is like robbing the world of the sun. - Cicero",
  "The function of wisdom is to discriminate between good and evil. - Cicero",
  "The enemy is within the gates; it is with our own luxury, our own folly, our own criminality that we have to contend. - Cicero",
  "For books are more than books, they are the life, the very heart and core of ages past, the reason why men lived and worked and died, the essence and quintessence of their lives. - Cicero",
];
const musoniusRufus = [
  "The person who has practiced philosophy as a cure for the soul knows that virtue is the greatest good. - Musonius Rufus",
  "Education and the search for truth are in a certain way a kind of philosophy. - Musonius Rufus",
  "We are all children of God and we have all been given a share of His divinity. - Musonius Rufus",
  "He who has a why to live can bear almost any how. - Musonius Rufus",
  "To relax the mind is to lose it. - Musonius Rufus",
  "One must practice the thing, not just talk about it. - Musonius Rufus",
  "Let no one tell me that words are too hard to understand or to memorize, for the uneducated know the verses of poets by heart. - Musonius Rufus",
  "One does not progress through simple learning alone, but through the application of what he has learned. - Musonius Rufus",
  "We should train ourselves to let go of the things we cannot control. - Musonius Rufus",
  "Virtue is not some end to be pursued; it is in itself a necessity of life. - Musonius Rufus",
  "There is no goal that cannot be reached by practicing virtue. - Musonius Rufus",
  "Do not seek to bring things to pass in accordance with your wishes, but wish for them as they are, and you will find them. - Musonius Rufus",
  "The wise man seeks always to live in harmony with nature. - Musonius Rufus",
  "The best way to defend oneself is not to do anything wrong. - Musonius Rufus",
  "The measure of a man is his ability to live in harmony with the universe. - Musonius Rufus",
  "Good actions give strength to ourselves and inspire good actions in others. - Musonius Rufus",
  "The wise man is content with his lot, whatever it may be, without wishing for what he has not. - Musonius Rufus",
  "The greatest wealth is to live content with little. - Musonius Rufus",
  "Do not explain your philosophy. Embody it. - Musonius Rufus",
  "To be even-minded is the greatest virtue. - Musonius Rufus",
  "The soul is dyed with the color of its thoughts. - Musonius Rufus",
  "The wise man does not grieve for what he has not, but rejoices in what he has. - Musonius Rufus",
  "Man is not worried by real problems so much as by his imagined anxieties about real problems. - Musonius Rufus",
  "The art of living is more like wrestling than dancing. - Musonius Rufus",
  "The purpose of life is to follow reason and virtue. - Musonius Rufus",
  "The only way to happiness is to cease worrying about things which are beyond the power of our will. - Musonius Rufus",
  "We cannot choose our external circumstances, but we can always choose how we respond to them. - Musonius Rufus",
  "The wise man is neither raised up by prosperity nor cast down by adversity. - Musonius Rufus",
  "If you want to improve, be content to be thought foolish and stupid. - Musonius Rufus",
  "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. - Musonius Rufus",
  "It is not what happens to you, but how you react to it that matters. - Musonius Rufus",
  "To accuse others for one's own misfortunes is a sign of want of education. To accuse oneself shows that one's education has begun. To accuse neither oneself nor others shows that one's education is complete. - Musonius Rufus",
  "The universe is change; our life is what our thoughts make it. - Musonius Rufus",
  "We are more often frightened than hurt; and we suffer more from imagination than from reality. - Musonius Rufus",
  "Wealth consists not in having great possessions, but in having few wants. - Musonius Rufus",
  "The whole future lies in uncertainty: live immediately. - Musonius Rufus",
  "Most powerful is he who has himself in his own power. - Musonius Rufus",
  "To live happily is an inward power of the soul. - Musonius Rufus",
  "He who has great power should use it lightly. - Musonius Rufus",
  "The wise man belongs to all countries, for the home of a great soul is the whole world. - Musonius Rufus",
  "A friend is a second self. - Musonius Rufus",
  "The measure of a man is the way he bears up under misfortune. - Musonius Rufus",
  "Nothing is more honorable than a grateful heart. - Musonius Rufus",
  "Accept whatever comes to you woven in the pattern of your destiny, for what could more aptly fit your needs? - Musonius Rufus",
  "True happiness is to enjoy the present, without anxious dependence upon the future. - Musonius Rufus",
  "The function of wisdom is to discriminate between good and evil. - Musonius Rufus",
  "To study philosophy is nothing but to prepare one's self to die. - Musonius Rufus",
  "Virtue alone is the good. - Musonius Rufus",
  "Happiness is a good flow of life. - Musonius Rufus",
];
const hierocles = [
  "We should train our minds to love virtue, not merely to follow it. - Hierocles",
  "The universe itself is a community of rational beings. - Hierocles",
  "To live consistently with nature, we must understand the nature of the whole universe. - Hierocles",
  "Happiness comes from within, not from external things. - Hierocles",
  "Wisdom is the knowledge of good and evil. - Hierocles",
  "Every virtue is a form of self-control. - Hierocles",
  "True freedom is found only in the mind. - Hierocles",
  "The wise man lives in harmony with nature and his own reason. - Hierocles",
  "The soul is the true self. - Hierocles",
  "The purpose of life is to live in accordance with nature. - Hierocles",
  "A good life is one that is lived in accordance with virtue. - Hierocles",
  "Virtue is the highest good. - Hierocles",
  "We must be kind to others and strive to help them as much as we can. - Hierocles",
  "The wise man is content with what he has. - Hierocles",
  "We must learn to control our desires and emotions. - Hierocles",
  "To be virtuous is to be happy. - Hierocles",
  "We should strive to improve ourselves and help others. - Hierocles",
  "The wise man does not seek wealth or power, but virtue. - Hierocles",
  "The true self is found in the soul, not the body. - Hierocles",
  "The wise man is always at peace with himself. - Hierocles",
  "We must strive to be virtuous in all aspects of our lives. - Hierocles",
  "The universe is a rational and ordered whole. - Hierocles",
  "True happiness is found in virtue. - Hierocles",
  "The wise man is indifferent to external goods. - Hierocles",
  "We must strive to live in harmony with nature. - Hierocles",
  "The soul is immortal. - Hierocles",
  "The wise man seeks to understand the nature of the universe. - Hierocles",
  "Virtue is the foundation of a good life. - Hierocles",
  "We must learn to be content with what we have. - Hierocles",
  "The wise man is free from fear and desire. - Hierocles",
  "We must strive to be virtuous in thought, word, and deed. - Hierocles",
  "The universe is a community of rational beings. - Hierocles",
  "True wisdom is the knowledge of good and evil. - Hierocles",
  "We must strive to live according to reason. - Hierocles",
  "The wise man is content with his lot. - Hierocles",
  "We must learn to control our emotions. - Hierocles",
  "The purpose of life is to live in accordance with nature. - Hierocles",
  "True happiness is found in the soul, not the body. - Hierocles",
  "The wise man seeks to help others. - Hierocles",
  "We must strive to be virtuous in all things. - Hierocles",
  "The soul is the true self. - Hierocles",
  "Virtue is the highest good. - Hierocles",
  "We must be kind to others and help them as much as we can. - Hierocles",
  "The wise man is always at peace with himself. - Hierocles",
  "We must learn to be content with what we have. - Hierocles",
  "The universe is a rational and ordered whole. - Hierocles",
  "True happiness is found in virtue. - Hierocles",
  "The wise man is indifferent to external goods. - Hierocles",
];
const gaiusMusoniusRufus = [
  "To relax the mind is to lose it. - Gaius Musonius Rufus",
  "Virtue is the only true good. - Gaius Musonius Rufus",
  "The best way to defend oneself is not to do anything wrong. - Gaius Musonius Rufus",
  "The wise man seeks always to live in harmony with nature. - Gaius Musonius Rufus",
  "One must practice the thing, not just talk about it. - Gaius Musonius Rufus",
  "The person who has practiced philosophy as a cure for the soul knows that virtue is the greatest good. - Gaius Musonius Rufus",
  "We should train ourselves to let go of the things we cannot control. - Gaius Musonius Rufus",
  "Virtue is not some end to be pursued; it is in itself a necessity of life. - Gaius Musonius Rufus",
  "There is no goal that cannot be reached by practicing virtue. - Gaius Musonius Rufus",
  "Do not seek to bring things to pass in accordance with your wishes, but wish for them as they are, and you will find them. - Gaius Musonius Rufus",
  "The wise man seeks always to live in harmony with nature. - Gaius Musonius Rufus",
  "Good actions give strength to ourselves and inspire good actions in others. - Gaius Musonius Rufus",
  "The wise man is content with his lot, whatever it may be, without wishing for what he has not. - Gaius Musonius Rufus",
  "The greatest wealth is to live content with little. - Gaius Musonius Rufus",
  "Do not explain your philosophy. Embody it. - Gaius Musonius Rufus",
  "To be even-minded is the greatest virtue. - Gaius Musonius Rufus",
  "The soul is dyed with the color of its thoughts. - Gaius Musonius Rufus",
  "The wise man does not grieve for what he has not, but rejoices in what he has. - Gaius Musonius Rufus",
  "Man is not worried by real problems so much as by his imagined anxieties about real problems. - Gaius Musonius Rufus",
  "The art of living is more like wrestling than dancing. - Gaius Musonius Rufus",
  "The purpose of life is to follow reason and virtue. - Gaius Musonius Rufus",
  "The only way to happiness is to cease worrying about things which are beyond the power of our will. - Gaius Musonius Rufus",
  "We cannot choose our external circumstances, but we can always choose how we respond to them. - Gaius Musonius Rufus",
  "The wise man is neither raised up by prosperity nor cast down by adversity. - Gaius Musonius Rufus",
  "If you want to improve, be content to be thought foolish and stupid. - Gaius Musonius Rufus",
  "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. - Gaius Musonius Rufus",
  "It is not what happens to you, but how you react to it that matters. - Gaius Musonius Rufus",
  "To accuse others for one's own misfortunes is a sign of want of education. To accuse oneself shows that one's education has begun. To accuse neither oneself nor others shows that one's education is complete. - Gaius Musonius Rufus",
  "The universe is change; our life is what our thoughts make it. - Gaius Musonius Rufus",
  "We are more often frightened than hurt; and we suffer more from imagination than from reality. - Gaius Musonius Rufus",
  "Wealth consists not in having great possessions, but in having few wants. - Gaius Musonius Rufus",
  "The whole future lies in uncertainty: live immediately. - Gaius Musonius Rufus",
  "Most powerful is he who has himself in his own power. - Gaius Musonius Rufus",
  "To live happily is an inward power of the soul. - Gaius Musonius Rufus",
  "He who has great power should use it lightly. - Gaius Musonius Rufus",
  "The wise man belongs to all countries, for the home of a great soul is the whole world. - Gaius Musonius Rufus",
  "A friend is a second self. - Gaius Musonius Rufus",
  "The measure of a man is the way he bears up under misfortune. - Gaius Musonius Rufus",
  "Nothing is more honorable than a grateful heart. - Gaius Musonius Rufus",
  "Accept whatever comes to you woven in the pattern of your destiny, for what could more aptly fit your needs? - Gaius Musonius Rufus",
  "True happiness is to enjoy the present, without anxious dependence upon the future. - Gaius Musonius Rufus",
  "The function of wisdom is to discriminate between good and evil. - Gaius Musonius Rufus",
  "To study philosophy is nothing but to prepare one's self to die. - Gaius Musonius Rufus",
  "Virtue alone is the good. - Gaius Musonius Rufus",
  "Happiness is a good flow of life. - Gaius Musonius Rufus",
  "The wise man is neither raised up by prosperity nor cast down by adversity. - Gaius Musonius Rufus",
  "We should train ourselves to let go of the things we cannot control. - Gaius Musonius Rufus",
  "Virtue is the only true good. - Gaius Musonius Rufus",
];

const quotes = [
  { zenoOfCitium },
  { epictetus },
  { senecaTheYounger },
  { marcusAurelius },
  { cleanthes },
  { chrysippus },
  { cicero },
  { musoniusRufus },
  { hierocles },
  { gaiusMusoniusRufus },
];

function getRandomQuote(): string {
  const randomWriter = quotes[Math.floor(Math.random() * quotes.length)];
  const writer = Object.values(randomWriter)[0];
  const randomQuote = writer[Math.floor(Math.random() * writer.length)];
  return randomQuote;
}
export { quotes, getRandomQuote };
